@startuml

entity user {
    * id: int <<generated>>
    --
    * telegram_id: int
    * username: varchar
    * correct_answers: int
    * tasks_answered: int
    * max_unlimited_score: int
}

@enduml